```{r}
#loading libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(timevis)
library(stringr)
```



```{r}
#loading data, renaming columns
data_copy <- read.csv("project_data.csv", na.strings = c("", "NA"))

colnames(data_copy) <- c("college", "source", "description", "link", "start", "date_event", 
                         "number_students", "scope_size", "reason", "cause", "tags", "against", "group_category", "group_name", "effect", "method", "location", "is_linked", "umbrella_tag", "text_ocr")

#making date information date format
data_copy$start =  as.Date(data_copy$start, format = "%Y-%m-%d")
```

```{r}
cbPalette <- c("#56B4E9", "#009E73", "#999999", "#E69F00",  "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

```

```{r}
#making pie chart of where the information is from 

data_copy_college_pie <- data_copy %>% 
  group_by(college) %>% 
  count() %>% 
  ungroup() %>%
  mutate(per = n/sum(n)) %>%
  mutate(per = per *100)

data_copy_college_pie$per <- round(data_copy_college_pie$per, 2)

ggplot(data_copy_college_pie, aes(x="", y = per, fill = college)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) + 
  labs(x = NULL, y = NULL, fill = NULL) +
  geom_text(aes(label = paste0(per,"%")), position = position_stack(vjust=0.5)) +
  theme_classic() +
  ggtitle("College archives where our source objects are from") +
  theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) +
  scale_fill_manual(values=cbPalette)
```


```{r}
#Bar plot for the size/scope of the protests, separated by college

#filtering out NA
data_bar <- data_copy[!(is.na(data_copy$scope_size)), ]

#selecting columns that matter to this plot
data_bar <- data_bar %>%
  select(college, scope_size)

#re-ordering factor so bar starts with small and ends with entire student body
data_bar$scope_size <- factor(data_bar$scope_size,levels = c("small", "medium", "large", "entire student body"))

#making table for the bar graph
tbl <- with(data_bar, table(college, scope_size))

#making plot
ggplot(as.data.frame(tbl), aes(factor(scope_size), Freq, fill = college)) +     
  geom_col() +
  labs(fill= "Size of the protest as the source objects describe") +
  xlab("Scope of protests") +
  ylab("Number of protests in each scope") + 
  theme(axis.title.x = element_text(hjust=-0.8),
        axis.title.y = element_text(vjust=0.8)) +
  theme_classic() +
  scale_fill_manual(values=cbPalette)
```


```{r}
#Pie chart for the size/scope of the protests, NOT separated by college

data_copy_scope_pie <- data_copy %>% 
  group_by(scope_size) %>% 
  count() %>% 
  ungroup() %>%
  mutate(per = n/sum(n)) %>%
  mutate(per = per * 100)

data_copy_scope_pie$per <- round(data_copy_scope_pie$per, 2)

data_copy_scope_pie$scope_size <- factor(data_copy_scope_pie$scope_size,levels = c("small", "medium", "large", "entire student body"))

ggplot(data_copy_scope_pie, aes(x="", y = per, fill = scope_size)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) + 
  labs(x = NULL, y = NULL, fill = NULL) +
  geom_text(aes(label = paste0(per,"%")), position = position_stack(vjust=0.5)) +
  theme_classic() +
  ggtitle("Size of the protest as the sources objects describe for both colleges") +
  theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) +
  scale_fill_manual(values=cbPalette)

```

```{r}
#pie chart for the size/scope of protest of Vassar

data_copy_scope_pie_vassar <- data_copy %>% 
  filter(college=="Vassar") %>%
  group_by(scope_size) %>% 
  count() %>% 
  ungroup() %>%
  mutate(per = n/sum(n)) %>%
  mutate(per = per * 100)

data_copy_scope_pie_vassar$per <- round(data_copy_scope_pie_vassar$per, 2)

data_copy_scope_pie_vassar$scope_size <- factor(data_copy_scope_pie_vassar$scope_size,levels = c("small", "medium", "large", "entire student body"))

ggplot(data_copy_scope_pie_vassar, aes(x="", y = per, fill = scope_size)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) + 
  labs(x = NULL, y = NULL, fill = NULL) +
  geom_text(aes(label = paste0(per,"%")), position = position_stack(vjust=0.5)) +
  theme_classic() +
  ggtitle("Size of the protest as the sources objects describe for Vassar") +
  theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) +
  scale_fill_manual(values=cbPalette)

```

```{r}
#pie chart for the size/scope of protest of Haverford

data_copy_scope_pie_haverford <- data_copy %>% 
  filter(college=="Haverford") %>%
  group_by(scope_size) %>% 
  count() %>% 
  ungroup() %>%
  mutate(per = n/sum(n))

data_copy_scope_pie_haverford$per <- round(data_copy_scope_pie_haverford$per, 2)

data_copy_scope_pie_haverford$scope_size <- factor(data_copy_scope_pie_haverford$scope_size,levels = c("small", "medium", "large", "entire student body"))


ggplot(data_copy_scope_pie_haverford, aes(x="", y = per, fill = scope_size)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) + 
  labs(x = NULL, y = NULL, fill = NULL) +
  geom_text(aes(label = paste0(per,"%")), position = position_stack(vjust=0.5)) +
  theme_classic() +
  ggtitle("Size of the protest as the sources objects describe for Haverford") +
  theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) +
  scale_fill_manual(values=cbPalette)

```

